language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3
install:
  - pip install $DJANGO
  - pip install -r test_requirements.txt
env:
  - DJANGO='django>=2,<2.1'
  - DJANGO='django>=2.1,<2.2'
  - DJANGO='django>=2.2,<3.0'
  - DJANGO='django>=3.0,<3.1'
jobs:
  exclude:
    - python: 3.5
      env: DJANGO='django>=3.0,<3.1'
    - python: pypy3
      env: DJANGO='django>=3.0,<3.1'
    - python: 3.8
      env: DJANGO='django>=2,<2.1'
script:
  - flake8
  - coverage run --source=collector run_tests.py
after_success:
  coveralls
